package bank;

import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class BankATM extends javax.swing.JFrame {
    BANK bank = new BANK();
/**
    private double hasil;
    private String answer;
    private double saldo;
    private int masukan;
    private String nama3;
    private int norek;

    public double getHasil() {
        return hasil;
    }

    public void setHasil(double hasil) {
        this.hasil = hasil;
    }

    public String getAnswer() {
        return answer;
    }

    public void setAnswer(String answer) {
        this.answer = answer;
    }

    public double getSaldo() {
        return saldo;
    }

    public void setSaldo(double saldo) {
        this.saldo = saldo;
    }

    public int getMasukan() {
        return masukan;
    }

    public void setMasukan(int masukan) {
        this.masukan = masukan;
    }

    public String getNama3() {
        return nama3;
    }

    public void setNama3(String nama3) {
        this.nama3 = nama3;
    }

    public int getNorek() {
        return norek;
    }

    public void setNorek(int norek) {
        this.norek = norek;
    }
    */
     BANK Bank = new BANK();
    
    public BankATM() {
        initComponents();
    }

    /**
     *
     * @param saldo
     */
    public BankATM(double saldo) {
     Bank.setSaldo(saldo);
    }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jColorChooser1 = new javax.swing.JColorChooser();
        jColorChooser2 = new javax.swing.JColorChooser();
        jColorChooser3 = new javax.swing.JColorChooser();
        jColorChooser4 = new javax.swing.JColorChooser();
        jColorChooser5 = new javax.swing.JColorChooser();
        jPanel1 = new javax.swing.JPanel();
        jtxtTampilan2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnClear = new javax.swing.JButton();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        btnTransfer = new javax.swing.JButton();
        btnCekSaldo = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnSimpan = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        btnAmbil = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Saldo anda saat ini adalah :");

        btnClear.setBackground(new java.awt.Color(255, 255, 255));
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 51, 255));
        setMaximumSize(new java.awt.Dimension(1280, 740));
        getContentPane().setLayout(null);

        btnTransfer.setBackground(new java.awt.Color(255, 153, 0));
        btnTransfer.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btnTransfer.setText("Transfer");
        btnTransfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransferActionPerformed(evt);
            }
        });
        getContentPane().add(btnTransfer);
        btnTransfer.setBounds(760, 220, 450, 140);

        btnCekSaldo.setBackground(new java.awt.Color(255, 153, 0));
        btnCekSaldo.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btnCekSaldo.setText("Cek Saldo");
        btnCekSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCekSaldoActionPerformed(evt);
            }
        });
        getContentPane().add(btnCekSaldo);
        btnCekSaldo.setBounds(70, 390, 450, 140);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("MENU");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(460, 130, 350, 80);

        btnSimpan.setBackground(new java.awt.Color(255, 153, 0));
        btnSimpan.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btnSimpan.setText("nabung");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        getContentPane().add(btnSimpan);
        btnSimpan.setBounds(760, 390, 450, 140);

        btnKeluar.setBackground(new java.awt.Color(255, 153, 0));
        btnKeluar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnKeluar.setText("<< Keluar");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });
        getContentPane().add(btnKeluar);
        btnKeluar.setBounds(60, 570, 450, 60);

        btnAmbil.setBackground(new java.awt.Color(255, 153, 0));
        btnAmbil.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btnAmbil.setText("Ambil");
        btnAmbil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAmbilActionPerformed(evt);
            }
        });
        getContentPane().add(btnAmbil);
        btnAmbil.setBounds(70, 220, 450, 140);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/9.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 1280, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        jtxtTampilan2.setText("");
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        /** String receipt = "Transaction Receipt\n";
        receipt += "Type: History\n";
        receipt += "Amount: " + masukan + "\n";
        receipt += "New Balance: " + saldo + "\n";
        JOptionPane.showMessageDialog(rootPane, receipt);*/
        dispose();
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void btnAmbilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAmbilActionPerformed
        ambil Ambil = new ambil();
        Ambil.setVisible(true);
        this.dispose();
        /**Bank.setMasukan(Integer.parseInt(JOptionPane.showInputDialog("Masukan nominal uang : ")));
        Bank.setSaldo(Bank.getHasil());
        Bank.setAnswer(String.format(" %,.2f ", Bank.getHasil()));
        jtxtTampilan2.setText(Bank.getAnswer())s;
        JOptionPane.showMessageDialog(rootPane,"Saldo Anda Saat Ini adalah :"+ Bank.getSaldo()+ "\n");

        String receipt = "Transaction Receipt\n";
        receipt += "Type: tarik tunai\n";
        receipt += "Amount: " + Bank.getMasukan() + "\n";
        receipt += "New Balance: " + Bank.getSaldo() + "\n";
        JOptionPane.showMessageDialog(rootPane, receipt);*/
    }//GEN-LAST:event_btnAmbilActionPerformed

    private void btnTransferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransferActionPerformed
        transfer Transfer = new transfer();
        Transfer.setVisible(true);
        this.dispose();
        /**  String nama3=JOptionPane.showInputDialog("Silahkan Masukan Nama ");
        String nomerRekening = JOptionPane.showInputDialog("Silahkan Masukan Nomer Rekening ");
        masukan = Integer.parseInt(JOptionPane.showInputDialog("Masukan nominal uang : "));
        if (saldo <= masukan) {
            JOptionPane.showMessageDialog(rootPane,"Maaf Saldo anda kurang !!!!!");
            JOptionPane.showConfirmDialog(null, " Apakah ingin lanjut");
            JOptionPane.showMessageDialog(rootPane,"Tambahkan Saldo Rekening Anda Terlebih Dahulu");
            System.exit(0);
        } else if (saldo >= masukan) {

        }
        hasil = saldo - masukan;
        saldo=hasil;
        answer = String.format(" %,.2f ", hasil);
        jtxtTampilan2.setText(answer);
        JOptionPane.showMessageDialog(rootPane,"Saldo Anda Saat Ini adalah :" + saldo+ "\n"+ "Berhasil transfer kepada nomer rekening " + nomerRekening + " sebesar :" + masukan+ "\n" + "atas Nama : " + nama3);

        String receipt = "Transaction Receipt\n";
        receipt += "Type: Transfer\n";
        receipt += "Amount: " + masukan + "\n";
        receipt += "New Balance: " + saldo + "\n";
        JOptionPane.showMessageDialog(rootPane, receipt);

        Bank.setNama3(JOptionPane.showInputDialog("Silahkan Masukan Nama "));
        Bank.setNorek(JOptionPane.showInputDialog("Silahkan Masukan Nomer Rekening "));
        Bank.setMasukan(Integer.parseInt(JOptionPane.showInputDialog("Masukan angka : ")));
        if (Bank.getSaldo() <= Bank.getMasukan()) {
            JOptionPane.showMessageDialog(rootPane,"Maaf Saldo anda kurang !!!!!");
            JOptionPane.showConfirmDialog(null, " Apakah ingin lanjut");
            JOptionPane.showMessageDialog(rootPane,"Tambahkan Saldo Rekening Anda Terlebih Dahulu");
            System.exit(0);
        } else if (Bank.getSaldo() >= Bank.getMasukan()) {

        }
        Bank.setHasil(Bank.getSaldo() - Bank.getMasukan());
        Bank.setSaldo(Bank.getHasil());
        Bank.setAnswer(String.format(" %,.2f ", Bank.getHasil()));
        jtxtTampilan2.setText(Bank.getAnswer());
        JOptionPane.showMessageDialog(rootPane,"Saldo Anda Saat Ini adalah :"+ Bank.getSaldo()+ "\n"+"Berhasil transfer kepada nomer rekening " + Bank.getNorek() + "atas nama "+Bank.getNama3()+"sebesar :"+ Bank.getMasukan());
        */

    }//GEN-LAST:event_btnTransferActionPerformed

    private void btnCekSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCekSaldoActionPerformed
        JOptionPane.showMessageDialog(rootPane, "Saldo Anda Saat Ini adalah :"+ Bank.getSaldo());
        //Bank.setHasil(); = Bank.setSaldo();
        Bank.setSaldo(Bank.getHasil());
        Bank.setAnswer(String.format(" %,.2f ",Bank.getSaldo()));
        jtxtTampilan2.setText(Bank.getAnswer());
    }//GEN-LAST:event_btnCekSaldoActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        //  Bank.setMasukan()= Integer.parseInt(JOptionPane.showInputDialog("Masukan angka : ");
            nabung Nabung = new nabung();
            Nabung.setVisible(true);
            this.dispose();

            /**Bank.setMasukan(Integer.parseInt(JOptionPane.showInputDialog("Masukan angka : ")));
            JOptionPane.showMessageDialog(rootPane,"Saldo Anda Saat Ini adalah :"+ (Bank.getSaldo() + Bank.getMasukan()));
            Bank.setHasil(Bank.getSaldo() + Bank.getMasukan());
            Bank.setSaldo(Bank.getHasil());
            Bank.setAnswer(String.format(" %,.2f ", Bank.getSaldo()));
            //answer = String.format(" %,.2f ",saldo);
            jtxtTampilan2.setText(Bank.getAnswer());

            String receipt = "Transaction Receipt\n";
            receipt += "Type: Deposit\n";
            receipt += "Amount: " + Bank.getMasukan() + "\n";
            receipt += "New Balance: " + Bank.getSaldo() + "\n";
            JOptionPane.showMessageDialog(rootPane, receipt);
            */
    }//GEN-LAST:event_btnSimpanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BankATM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BankATM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BankATM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BankATM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BankATM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAmbil;
    private javax.swing.JButton btnCekSaldo;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTransfer;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JColorChooser jColorChooser2;
    private javax.swing.JColorChooser jColorChooser3;
    private javax.swing.JColorChooser jColorChooser4;
    private javax.swing.JColorChooser jColorChooser5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JTextField jtxtTampilan2;
    // End of variables declaration//GEN-END:variables

    private void setHasil() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
