/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bank;
import javax.swing.JOptionPane;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JComboBox;
/**
 *
 * @author user
 */
public class transfer extends javax.swing.JFrame {
 
     BANK Bank = new BANK();
     int Tinput;
    String Tjumlah;
    String tnama;
    String tnorek;
    String type;
    /**
     *
     */
    public transfer() {
        initComponents();
    }

    /**
     *
     * @param saldo
     */
    public transfer(double saldo) {
      Bank.setSaldo(saldo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bank = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        norek = new javax.swing.JTextField();
        nama = new javax.swing.JTextField();
        nominal = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(null);

        bank.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bank.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "bank BCA", "bank BRI", "bank Mandiri", "bank syariah" }));
        bank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bankActionPerformed(evt);
            }
        });
        getContentPane().add(bank);
        bank.setBounds(490, 190, 420, 60);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("jenis bank:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(290, 200, 190, 50);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("nama:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(290, 360, 180, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("nomer rekening:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(280, 280, 200, 50);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("jumlah transfer:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(280, 440, 190, 40);

        norek.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        norek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                norekActionPerformed(evt);
            }
        });
        getContentPane().add(norek);
        norek.setBounds(490, 270, 420, 60);

        nama.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaActionPerformed(evt);
            }
        });
        getContentPane().add(nama);
        nama.setBounds(490, 350, 420, 60);

        nominal.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        nominal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nominalActionPerformed(evt);
            }
        });
        getContentPane().add(nominal);
        nominal.setBounds(490, 430, 420, 60);

        jPanel1.setBackground(new java.awt.Color(255, 153, 51));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton1.setText("TRANSFER");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(293, 293, 293)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(327, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(375, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(160, 140, 960, 490);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/9.png"))); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(1, 0, 1280, 730);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Bank.setMasukan(Integer.parseInt(nominal.getText()));
        Bank.setJenis(bank.getSelectedItem().toString());
        Bank.setNama3(nama.getText());
        
        Bank.setNorek(norek.getText());
        
        //String nama3=JOptionPane.showInputDialog("Silahkan Masukan Nama ");
        // String nomerRekening = JOptionPane.showInputDialog("Silahkan Masukan Nomer Rekening ");
        //masukan = Integer.parseInt(JOptionPane.showInputDialog("Masukan nominal uang : "));
        if (Bank.getSaldo() <= Bank.getMasukan()) {
            JOptionPane.showMessageDialog(rootPane,"Maaf Saldo anda kurang !!!!!");
            JOptionPane.showConfirmDialog(null, " Apakah ingin lanjut");
            JOptionPane.showMessageDialog(rootPane,"Tambahkan Saldo Rekening Anda Terlebih Dahulu");
            System.exit(0);
        } else if (Bank.getSaldo() >= Bank.getMasukan()) {
            Bank.setHasil(Bank.getSaldo() - Bank.getMasukan());
            Bank.setSaldo(Bank.getHasil());
            Bank.setAnswer(String.format(" %,.2f ", Bank.getHasil()));
        }

        JOptionPane.showMessageDialog(rootPane,"Saldo Anda Saat Ini adalah :" + Bank.getSaldo() + "\n"+ "apa anda yakin akan melakukan transaksi kepada nomer rekening " + Bank.getNorek() + "\n" + " sebesar :" + Bank.getMasukan() + "\n" + "atas Nama : " + Bank.getNama3()+"\n"+"bank tujuan :"+ Bank.getJenis());
        int Tinput = Bank.getMasukan();
        String Tjumlah = Bank.getAnswer();
        String tnama = Bank.getNama3();
        String tnorek = Bank.getNorek();
        String type = Bank.getJenis();
       btransfer bt = new btransfer(Tjumlah, Tinput,tnama,tnorek,type);
       bt.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void nominalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nominalActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_nominalActionPerformed

    private void namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaActionPerformed
       
    }//GEN-LAST:event_namaActionPerformed

    private void norekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_norekActionPerformed
       
    }//GEN-LAST:event_norekActionPerformed

    private void bankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bankActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_bankActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(transfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(transfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(transfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(transfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new transfer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> bank;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField nominal;
    private javax.swing.JTextField norek;
    // End of variables declaration//GEN-END:variables

}
